### ISSUE TITLE
Failed to activate the django-templates package

### ISSUE THREAD

**Issue by JshWright** [benjohnson/atom-django-templates#24]
[Enter steps to reproduce below:]
1. Install django-templates...

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [django-templates](https://github.com/benjohnson/atom-django-templates) package, v0.5.0
### Stack Trace

Failed to activate the django-templates package

```
At Cannot read property 'scopeName' of undefined

TypeError: Cannot read property 'scopeName' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:130:30)
  at DisplayBuffer.module.exports.DisplayBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1151:35)
  at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2248:33)
  at /Users/josh/.atom/packages/django-templates/django-templates.coffee:28:20
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:276:9)
  at DjangoTemplates.watchEditors (/Users/josh/.atom/packages/django-templates/django-templates.coffee:17:20)
  at DjangoTemplates.activate (/Users/josh/.atom/packages/django-templates/django-templates.coffee:14:6)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
     -1:11.9.0 grammar-selector:show (atom-text-editor.editor)
     -1:09.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:03.6.0 grammar-selector:show (atom-text-editor.editor.is-focused)
  2x -1:01.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  },
  "django-templates": {
    "defaultToDjangoTemplatesForFilePathsContaining": [
      "templates"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
api-blueprint-preview, v0.5.1
django-templates, v0.5.0
go-plus, v3.3.11
linter, v0.12.7
linter-flake8, v1.4.2
linter-pep8, v0.2.0
minimap, v4.10.0

# Dev
No dev packages
```

**Comment by furins** [comment]
+1 same here.
possibly related: https://github.com/atom/atom/issues/6235
